name: macos-share-cpm

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
env:
  ALIEN_INSTALL_TYPE: share
  
jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure
