name: macos-noenv-cpanminus

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          brew install perl
          curl https://cpanmin.us | perl - App::cpanminus -n
          echo "##[add-path]/Users/runner/perl5/bin"
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps .
